# Generated by Django 2.1.5 on 2023-09-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField()),
                ('storage', models.BooleanField()),
                ('graphics', models.CharField(max_length=20)),
                ('Wireless', models.CharField(max_length=20)),
                ('usb_port', models.CharField(max_length=20)),
                ('Battery', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=50)),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
