# Generated by Django 2.1.5 on 2023-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230902_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.CharField(max_length=10),
        ),
    ]
