# Generated by Django 2.1.5 on 2023-09-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230902_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(default=0),
        ),
    ]
