# Generated by Django 2.1.5 on 2023-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20230904_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='screen_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
